/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as FormularioCodigoRouteImport } from './routes/formulario.$codigo'
import { Route as RelatorioCodigoRouteImport } from './routes/relatorio.$codigo'
import { Route as AuthenticatedAdminApiRouteImport } from './routes/_authenticated/admin_.api'
import { Route as AuthenticatedAdminBaseRouteImport } from './routes/_authenticated/admin_.base'
import { Route as AuthenticatedAdminPerguntasRouteImport } from './routes/_authenticated/admin_.perguntas'
import { Route as AuthenticatedAdminPromptRouteImport } from './routes/_authenticated/admin_.prompt'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin_.usuarios'
import { Route as AuthenticatedAdminDiagnosticoIdRouteImport } from './routes/_authenticated/admin_.diagnostico.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FormularioCodigoRoute = FormularioCodigoRouteImport.update({
  id: '/formulario/$codigo',
  path: '/formulario/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioCodigoRoute = RelatorioCodigoRouteImport.update({
  id: '/relatorio/$codigo',
  path: '/relatorio/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminApiRoute = AuthenticatedAdminApiRouteImport.update({
  id: '/admin_/api',
  path: '/admin/api',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBaseRoute = AuthenticatedAdminBaseRouteImport.update({
  id: '/admin_/base',
  path: '/admin/base',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPerguntasRoute =
  AuthenticatedAdminPerguntasRouteImport.update({
    id: '/admin_/perguntas',
    path: '/admin/perguntas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPromptRoute =
  AuthenticatedAdminPromptRouteImport.update({
    id: '/admin_/prompt',
    path: '/admin/prompt',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin_/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDiagnosticoIdRoute =
  AuthenticatedAdminDiagnosticoIdRouteImport.update({
    id: '/admin_/diagnostico/$id',
    path: '/admin/diagnostico/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/formulario/$codigo': typeof FormularioCodigoRoute
  '/relatorio/$codigo': typeof RelatorioCodigoRoute
  '/admin/api': typeof AuthenticatedAdminApiRoute
  '/admin/base': typeof AuthenticatedAdminBaseRoute
  '/admin/perguntas': typeof AuthenticatedAdminPerguntasRoute
  '/admin/prompt': typeof AuthenticatedAdminPromptRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/diagnostico/$id': typeof AuthenticatedAdminDiagnosticoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/formulario/$codigo': typeof FormularioCodigoRoute
  '/relatorio/$codigo': typeof RelatorioCodigoRoute
  '/admin/api': typeof AuthenticatedAdminApiRoute
  '/admin/base': typeof AuthenticatedAdminBaseRoute
  '/admin/perguntas': typeof AuthenticatedAdminPerguntasRoute
  '/admin/prompt': typeof AuthenticatedAdminPromptRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/diagnostico/$id': typeof AuthenticatedAdminDiagnosticoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/formulario/$codigo': typeof FormularioCodigoRoute
  '/relatorio/$codigo': typeof RelatorioCodigoRoute
  '/_authenticated/admin_/api': typeof AuthenticatedAdminApiRoute
  '/_authenticated/admin_/base': typeof AuthenticatedAdminBaseRoute
  '/_authenticated/admin_/perguntas': typeof AuthenticatedAdminPerguntasRoute
  '/_authenticated/admin_/prompt': typeof AuthenticatedAdminPromptRoute
  '/_authenticated/admin_/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin_/diagnostico/$id': typeof AuthenticatedAdminDiagnosticoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/formulario/$codigo'
    | '/relatorio/$codigo'
    | '/admin/api'
    | '/admin/base'
    | '/admin/perguntas'
    | '/admin/prompt'
    | '/admin/usuarios'
    | '/admin/diagnostico/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/formulario/$codigo'
    | '/relatorio/$codigo'
    | '/admin/api'
    | '/admin/base'
    | '/admin/perguntas'
    | '/admin/prompt'
    | '/admin/usuarios'
    | '/admin/diagnostico/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/formulario/$codigo'
    | '/relatorio/$codigo'
    | '/_authenticated/admin_/api'
    | '/_authenticated/admin_/base'
    | '/_authenticated/admin_/perguntas'
    | '/_authenticated/admin_/prompt'
    | '/_authenticated/admin_/usuarios'
    | '/_authenticated/admin_/diagnostico/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FormularioCodigoRoute: typeof FormularioCodigoRoute
  RelatorioCodigoRoute: typeof RelatorioCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/formulario/$codigo': {
      id: '/formulario/$codigo'
      path: '/formulario/$codigo'
      fullPath: '/formulario/$codigo'
      preLoaderRoute: typeof FormularioCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio/$codigo': {
      id: '/relatorio/$codigo'
      path: '/relatorio/$codigo'
      fullPath: '/relatorio/$codigo'
      preLoaderRoute: typeof RelatorioCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_/api': {
      id: '/_authenticated/admin_/api'
      path: '/admin/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AuthenticatedAdminApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/base': {
      id: '/_authenticated/admin_/base'
      path: '/admin/base'
      fullPath: '/admin/base'
      preLoaderRoute: typeof AuthenticatedAdminBaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/perguntas': {
      id: '/_authenticated/admin_/perguntas'
      path: '/admin/perguntas'
      fullPath: '/admin/perguntas'
      preLoaderRoute: typeof AuthenticatedAdminPerguntasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/prompt': {
      id: '/_authenticated/admin_/prompt'
      path: '/admin/prompt'
      fullPath: '/admin/prompt'
      preLoaderRoute: typeof AuthenticatedAdminPromptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/usuarios': {
      id: '/_authenticated/admin_/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/diagnostico/$id': {
      id: '/_authenticated/admin_/diagnostico/$id'
      path: '/admin/diagnostico/$id'
      fullPath: '/admin/diagnostico/$id'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminApiRoute: typeof AuthenticatedAdminApiRoute
  AuthenticatedAdminBaseRoute: typeof AuthenticatedAdminBaseRoute
  AuthenticatedAdminPerguntasRoute: typeof AuthenticatedAdminPerguntasRoute
  AuthenticatedAdminPromptRoute: typeof AuthenticatedAdminPromptRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminDiagnosticoIdRoute: typeof AuthenticatedAdminDiagnosticoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminApiRoute: AuthenticatedAdminApiRoute,
  AuthenticatedAdminBaseRoute: AuthenticatedAdminBaseRoute,
  AuthenticatedAdminPerguntasRoute: AuthenticatedAdminPerguntasRoute,
  AuthenticatedAdminPromptRoute: AuthenticatedAdminPromptRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminDiagnosticoIdRoute: AuthenticatedAdminDiagnosticoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FormularioCodigoRoute: FormularioCodigoRoute,
  RelatorioCodigoRoute: RelatorioCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
