/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormularioCodigoRouteImport } from './routes/formulario.$codigo'
import { Route as RelatorioCodigoRouteImport } from './routes/relatorio.$codigo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularioCodigoRoute = FormularioCodigoRouteImport.update({
  id: '/formulario/$codigo',
  path: '/formulario/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioCodigoRoute = RelatorioCodigoRouteImport.update({
  id: '/relatorio/$codigo',
  path: '/relatorio/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formulario/$codigo': typeof FormularioCodigoRoute
  '/relatorio/$codigo': typeof RelatorioCodigoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formulario/$codigo': typeof FormularioCodigoRoute
  '/relatorio/$codigo': typeof RelatorioCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formulario/$codigo': typeof FormularioCodigoRoute
  '/relatorio/$codigo': typeof RelatorioCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/formulario/$codigo' | '/relatorio/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/formulario/$codigo' | '/relatorio/$codigo'
  id: '__root__' | '/' | '/formulario/$codigo' | '/relatorio/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormularioCodigoRoute: typeof FormularioCodigoRoute
  RelatorioCodigoRoute: typeof RelatorioCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulario/$codigo': {
      id: '/formulario/$codigo'
      path: '/formulario/$codigo'
      fullPath: '/formulario/$codigo'
      preLoaderRoute: typeof FormularioCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio/$codigo': {
      id: '/relatorio/$codigo'
      path: '/relatorio/$codigo'
      fullPath: '/relatorio/$codigo'
      preLoaderRoute: typeof RelatorioCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormularioCodigoRoute: FormularioCodigoRoute,
  RelatorioCodigoRoute: RelatorioCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
