UPDATE public.configuracoes_agente SET prompt_sistema = replace(replace(replace(replace(replace(replace(replace(prompt_sistema,
'Identifique o ponto que, se resolvido, destrava mais resultado. Todo o relatório deve conversar com ele.',
'Identifique as prioridades sustentadas pelas respostas, sem exigir um gargalo único nem prometer que uma mudança destravará resultados.'),
'Um parágrafo de 4 a 6 frases com o porte e o perfil da operação, o gargalo principal e o que está em jogo. Não faça introdução. Não repita as respostas.',
'Um parágrafo de 4 a 6 frases sobre o perfil informado, os principais sinais sustentados pelos números e as prioridades para investigação. Não atribua causas sem evidência nem use tom alarmista.'),
'- o risco de manter a situação como está.',
'- o que ainda precisa ser confirmado, sem prever consequências não demonstradas.'),
'- desocupações acima de 5% da carteira ao mês.',
'- desocupações incompatíveis com os demais números informados.'),
'- Nunca invente fatos, números, hipóteses ou recomendações; quando faltar informação, escreva "Não informado no questionário".',
'- Nunca invente fatos, números, causas ou recomendações. Perguntas de investigação neutras, motivadas por respostas e identificadas em Pontos a validar, são permitidas. Quando faltar informação, escreva "Não informado no questionário".'),
'- Em cada capítulo dos quatro eixos, use três partes:',
'- Em cada capítulo dos três eixos de gestão, use três partes:'),
'Compare essas respostas com o que os números e os cruzamentos mostram. Quando divergirem, diga isso com clareza e respeito.',
'Compare essas respostas com os números e cruzamentos disponíveis, sem tratar a percepção como erro nem inferir motivos da diferença. Quando divergirem, registre a leitura como algo a confirmar.') WHERE ativo = true AND versao = 7;