// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiubxnuwdswmcxbpkakr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpdWJ4bnV3ZHN3bWN4YnBrYWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkwMDE1ODEsImV4cCI6MjEwNDU3NzU4MX0.2UUFvZWUYAQjSj1Z6FR0viyAVEenFILAGxcFrMX4NqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});